metadata_dir = "/var/lib/garage/data/meta"
data_dir = "/var/lib/garage/data/data"
db_engine = "sqlite"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"

s3_api = { api_bind_addr = "[::]:3900", s3_region = "garage", root_domain = ".s3.garage.localhost" }
s3_web = { bind_addr = "[::]:3902", root_domain = ".web.garage.localhost" }
admin = { api_bind_addr = "[::]:3903" }
