"""initial_schema

Revision ID: 8dd7356e57d6
Revises: 
Create Date: 2026-06-06 13:52:29.504215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd7356e57d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('raw_prompt', sa.Text(), nullable=False),
    sa.Column('upsampled_prompt', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_history_id'), 'generation_history', ['id'], unique=False)
    op.create_index(op.f('ix_generation_history_timestamp'), 'generation_history', ['timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_history_timestamp'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_id'), table_name='generation_history')
    op.drop_table('generation_history')
    # ### end Alembic commands ###
